### ISSUE TITLE
re-use globi taxon suggestor

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/effechecka#16]
@jhammock suggested to re-use the taxon selector widget from http://globalbioticinteractions.org when adding taxa to the taxon selector on http://jhpoelen.github.io/effechecka .

**Comment by jhammock** [comment]
How easy is this? I'd like to send some folks to have a look at the trait selector, but I suspect all they will notice is the Terrifying Shower of Names. If sticking in the globi suggestor in its place would be quick/easy, I will wait for that...

**Comment by jhpoelen** [comment]
@jhammock I'll have a look in the next couple of days. . . stay tuned!

**Comment by jhpoelen** [comment]
@jhammock I've introduced a (minimalist) taxon selector similar to the one of http://www.globalbioticinteractions.org . I hope this is a bit less overwhelming. Please comment / re-open if this needs a little more work.

![screen shot 2015-10-02 at 4 17 04 pm](https://cloud.githubusercontent.com/assets/1084872/10259788/47d1d84c-6921-11e5-900f-0295687dc6c8.png)
