### ISSUE TITLE
csv checklist download should contain a separate column with most specific taxon

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/effechecka#17]
@jhammock suggested to include the most specific taxon in the csv download. 

Currently we have downloads like:

taxon path | count |
--- | ---
Animalia ...  Primates ... Homo sapiens | 123

and the suggested format is:

taxon | taxon path | count |
--- | --- | ---
Homo sapiens | Animalia ... Primates ... Homo sapiens | 123

**Comment by jhpoelen** [comment]
This feature is now available! Please re-open if not implemented as suggested.

**Comment by jhammock** [comment]
perfect, thanks!
