### ISSUE TITLE
What about showing existing queries?  Or, the most popular ones?

### ISSUE THREAD

**Issue by mariestuder** [jhpoelen/effechecka#19]
I'm wondering if it would make any sense to have a list of queries that have already been run?  I suppose the spatial selection is often so unique, that this might not make sense.  However, I could imagine there might be some popular areas and perhaps those could be shown as ready for download.  For example, birds of the San Francisco Bay area or something??  I guess this is less of an "issue" and more of a brainstorm!

**Comment by jhpoelen** [comment]
@mariestuder I've added some example queries in the effechecka home page at http://jhpoelen.github.io/effechecka : [small birds and mammals of San Francisco Bay Area](http://jhpoelen.github.io/effechecka#geometry=POLYGON((-121.75048828124999 38.1777509666256%2C-121.75048828124999 37.13404537126446%2C-122.78320312499999 37.13404537126446%2C-122.78320312499999 38.1777509666256%2C-121.75048828124999 38.1777509666256))&hasSpatialIssue=false&height=120&lat=37.65773212628274&limit=20&lng=-122.26684570312499&scientificName=Aves%2CMammalia&taxonSelector=Aves%2CMammalia&traitSelector=bodyMass < 50 g&width=94&wktString=ENVELOPE(-122.78320312499999%2C-121.75048828124999%2C38.1777509666256%2C37.13404537126446)&zoom=7) and [big sharks of the Gulf of Mexico](http://jhpoelen.github.io/effechecka#geometry=POLYGON((-80.595703125%2031.05293398570514%2C-80.595703125%2018.312810846425442%2C-97.822265625%2018.312810846425442%2C-97.822265625%2031.05293398570514%2C-80.595703125%2031.05293398570514))&hasSpatialIssue=false&height=160&lat=24.84656534821976&limit=20&lng=-89.20898437499999&scientificName=Elasmobranchii&taxonSelector=Elasmobranchii&traitSelector=bodyMass%20%3E%2010%20kg&width=196&wktString=ENVELOPE(-97.822265625%2C-80.595703125%2C31.05293398570514%2C18.312810846425442)&zoom=4) . 

Hope this will help! Please comment/re-open if you feel this needs a little more attention.
