### ISSUE TITLE
link taxon names to EOL page ids

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/effechecka#25]
In order to do #24 , we need to associate names from the effachecklist to EOL page ids.

@jrice @HudaSoliman - please confirm that eol taxon ids are needed to use collection write apis.

**Comment by JRice** [comment]
Yes, that is absolutely the case. EOL taxing concept ids only.

**Comment by jhpoelen** [comment]
@JRice thanks for confirming!

**Comment by jhpoelen** [comment]
Linking to eol page ids has been implemented using http://resolver.globalnames.org . Thanks @dimus !

**Comment by jhammock** [comment]
@jhpoelen can you provide an example of a query for this? The link in the prototype is not showing me one like the JSON link does. Thanks!

**Comment by jhpoelen** [comment]
@jhammock as discussed, the name linking is provided by http://resolver.globalnames.org/api . For javascript client implementation, see https://github.com/effechecka/effechecka.github.io/blob/9526b7b3a4bb36fcdc7493e6012e57cd315212c0/checklist.js and https://github.com/jhpoelen/node-taxon .

Here's an example of a query url: http://resolver.globalnames.org/name_resolvers.json?names=Poecile%20atricapillus%20(Linnaeus%2C%201766)%7CTurdus%20migratorius%20Linnaeus%2C%201766%7CCyanocitta%20cristata%20(Linnaeus%2C%201758)%7CCorvus%20brachyrhynchos%20Brehm%2C%201822%7CCardinalis%20cardinalis%20(Linnaeus%2C%201758)%7CZenaida%20macroura%20(Linnaeus%2C%201758)%7CMelospiza%20melodia%20(A.%20Wilson%2C%201810)%7CSpinus%20tristis%20(Linnaeus%2C%201758)%7CBaeolophus%20bicolor%20(Linnaeus%2C%201766)%7CPicoides%20pubescens%20(Linnaeus%2C%201766)%7CLarus%20argentatus%20Pontoppidan%2C%201763%7CAnas%20platyrhynchos%20Linnaeus%2C%201758%7CBranta%20canadensis%20(Linnaeus%2C%201758)%7CPasser%20domesticus%20(Linnaeus%2C%201758)%7CSitta%20carolinensis%20Latham%2C%201790%7CAgelaius%20phoeniceus%20(Linnaeus%2C%201766)%7CQuiscalus%20quiscula%20(Linnaeus%2C%201758)%7CSturnus%20vulgaris%20Linnaeus%2C%201758%7CLarus%20delawarensis%20Ord%2C%201815%7CLarus%20marinus%20Linnaeus%2C%201758%7CHaemorhous%20Swainson%2C%201837%7CDumetella%20carolinensis%20(Linnaeus%2C%201766)%7CJunco%20hyemalis%20(Linnaeus%2C%201758)%7CPhalacrocorax%20auritus%20(Lesson%2C%201831)%7CButeo%20jamaicensis%20(Gmelin%2C%201788)%7CColaptes%20auratus%20(Linnaeus%2C%201758)%7CAnas%20rubripes%20Brewster%2C%201902%7CArdea%20herodias%20Linnaeus%2C%201758%7CMimus%20polyglottos%20(Linnaeus%2C%201758)%7CZonotrichia%20albicollis%20(Gmelin%2C%201789)%7CThryothorus%20ludovicianus%20(Latham%2C%201790)%7CTachycineta%20bicolor%20(Vieillot%2C%201808)%7CMelanerpes%20carolinus%20(Linnaeus%2C%201758)%7CColumba%20livia%20Gmelin%2C%201789%7CSpizella%20passerina%20(Bechstein%2C%201798)%7CSomateria%20mollissima%20(Linnaeus%2C%201758)%7CBucephala%20albeola%20(Linnaeus%2C%201758)%7CSayornis%20phoebe%20(Latham%2C%201790)%7CSetophaga%20coronata%7CGeothlypis%20trichas%20(Linnaeus%2C%201766)%7CMergus%20serrator%20Linnaeus%2C%201758%7CCygnus%20olor%20(Gmelin%2C%201789)%7CGavia%20immer%20(Brunnich%2C%201764)%7CBombycilla%20cedrorum%20Vieillot%2C%201808%7CPicoides%20villosus%20(Linnaeus%2C%201766)%7CMolothrus%20ater%20(Boddaert%2C%201783)%7CIcterus%20galbula%20(Linnaeus%2C%201758)%7CSetophaga%20petechia%7CTringa%20melanoleuca%20(Gmelin%2C%201789)%7CPipilo%20erythrophthalmus%20(Linnaeus%2C%201758)&data_source_ids=12 .
