### ISSUE TITLE
(manual) limit list of items saved to EOL collection

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/effechecka#28]
from @jhammock 

Considering the WAPI capacity limitations, should we consider truncating the checklist import after a certain number of taxa? Jorrit, I got 34 fishes without a hiccup; where would you want to cut it off, based on your WAPI experience so far? We could raise it later, but we may always want some kind of limit, if we don't want million-taxa lists loaded/attempted

**Comment by jhpoelen** [comment]
and from @jhammock

And is it worth offering the user a manual taxon number cutoff for the collection import? (again, if it's easy)

**Comment by jhammock** [comment]
Sounds good to me. Suggested default = Sensible Generic Limit, or total # of retrieved records if less?

**Comment by jhammock** [comment]
Asked for 6 results from this query in my collection:

http://www.effechecka.org/#geometry=POLYGON%28%28-82.353515625%2030.221101852485987%2C-82.353515625%2027.916766641249065%2C-84.990234375%2027.916766641249065%2C-84.990234375%2030.221101852485987%2C-82.353515625%2030.221101852485987%29%29&hasSpatialIssue=false&height=30&lat=29.075375179558346&limit=20&lng=-83.671875&scientificName=Elasmobranchii&taxonSelector=Elasmobranchii&traitSelector=&width=30&wktString=ENVELOPE%28-84.990234375%2C-82.353515625%2C30.221101852485987%2C27.916766641249065%29&zoom=4

and got 2, a reasonable family level summary of my first 6 results...

http://eol.org/collections/119618
