### ISSUE TITLE
add link back to effechecka in collection description

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/effechecka#30]
inspired from feedback request email from @jhammock - which included a link to the original effechecka url describing the checklist selection criteria.

The idea is to include a link to the effechecka query in the collection description

**Comment by jhammock** [comment]
good idea. Possible hint text: "re-create this regional search with currently available data" ? (collection descriptions will take <a> tags)

**Comment by jhammock** [comment]
and link to collection appears on search page; nice!
