### ISSUE TITLE
nobody home in the arctic

### ISSUE THREAD

**Issue by jhammock** [jhpoelen/effechecka#33]
Hmm... still experimenting, but wanted to start documenting at least. I got zero taxon and occurrence results from the two searches below, which is surprising since both gbif and idigbio have records that seem to match:

http://www.effechecka.org/#geometry=POLYGON%28%2887.1875%2087.04309838968054%2C87.1875%2055.7765730186677%2C-243.28125%2055.7765730186677%2C-243.28125%2087.04309838968054%2C87.1875%2087.04309838968054%29%29&hasSpatialIssue=false&height=202&lat=79.81230226556366&limit=20&lng=-78.046875&scientificName=Aves%2CMammalia%2CMammalia&taxonSelector=Aves%2CMammalia%2CMammalia&traitSelector=&width=470&wktString=ENVELOPE%28-243.28125%2C87.1875%2C87.04309838968054%2C55.7765730186677%29&zoom=1

http://www.effechecka.org/#geometry=POLYGON%28%2887.1875%2087.04309838968054%2C87.1875%2055.7765730186677%2C-243.28125%2055.7765730186677%2C-243.28125%2087.04309838968054%2C87.1875%2087.04309838968054%29%29&hasSpatialIssue=false&height=202&lat=79.81230226556366&limit=20&lng=-78.046875&scientificName=Aves%2CMammalia%2CMammalia&taxonSelector=Aves%2CMammalia%2CMammalia&traitSelector=&width=470&wktString=ENVELOPE%28-243.28125%2C87.1875%2C87.04309838968054%2C55.7765730186677%29&zoom=1

**Comment by jhpoelen** [comment]
@jhammock root cause for this issue was that the longitudes weren't restricted to [-180, 180] range causing a bunch of freak-outs of data apis. Now, whenever an out of range longitude is encountered, the value is projected in the range. For instance, longitude -270 will be translated to a longitude of 90.

**Comment by jhammock** [comment]
Birds are home in the Arctic! Also a few mammals. Nice :)

**Comment by jhpoelen** [comment]
@jhammock just fixed a bug introduced by this "fix" causing the checklist generator to invert the longitude selection (e.g. select the world except for Boston longitudes vs only Boston area longitudes). For clarity, I added the selected areas in their "nerdy" wktString format below the map.

**Comment by jhpoelen** [comment]
Found my spatial selection issues. Re-opening.

**Comment by jhpoelen** [comment]
In addition to basic dateline "wrapping" (term used in GIS community) for checklist generation, I've addressed an issue that helps to select a complete longitude range across all latitudes (-90 <= lat <= 90). With this, I believe that we can generate meaningful checklists that cross datelines and are close to the poles. Please comment if you feel this is not the case.

Also, I've documented the limitation of the GBIF API (used in the occurrence section). Apparently, GBIF API does *not* support dateline wrapping and produces results for the inverted longitude selection. The full limitation text for GBIF section is:

-------
Known limitations (a) Only the top 20 matching occurrence records are provided for performance and simplicity sake. (b) The items in the list correspond to individual GBIF occurrence records that were recorded within the given area and the first taxonomic constraint (e.g. if "Aves" and "Insecta" are selected, only "Aves" is applied). So, the list may contain duplicates and is not ordered in any way. (c) GBIF API does not support spatial selections that cross the dateline (e.g. a box that covers US and Japan, but not Europe). Instead, GBIF inverts the longitudinal selection criteria, leading to unexpected results. The checklist generation does support dateline wrapping.

**Comment by jhammock** [comment]
Fantastic. Were you able to report the inversion problem to GBIF, or should I seek a communication channel? I'm surprised this has gone unnoticed so long...

**Comment by jhpoelen** [comment]
Just sent an email to GBIF API mailing list.
