### ISSUE TITLE
when checklist is empty, show something like "0" results.

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/effechecka#39]

**Comment by jhammock** [comment]
"Your search retrieved zero results. Bummer! You might try simplifying your search. 

Search again without body mass filters?" (handy link, show this part only if body mass filters were present?)

**Comment by jhpoelen** [comment]
Thanks for your suggestion. I've implemented a first pass at it. On an empty checklist, the page displays "The checklist you've requested contains no items. Bummer! You might want to try changing your search parameters.". When the checklist is empty and trait selectors are used, a button is included that removes all trait selectors and requests the associated checklist (see screenshot below). Please comment if you have ideas on how to make this better.
![screen shot 2015-11-11 at 1 10 45 pm](https://cloud.githubusercontent.com/assets/1084872/11103171/b11f3592-8875-11e5-8351-851890e6cf29.png)

**Comment by jhpoelen** [comment]
PS Here's a pre-calculated empty checklist I used: http://www.effechecka.org/#height=200&lat=38.89103282648849&limit=20&lng=-76.915283203125&taxonSelector=Insecta&traitSelector=bodyMass%20%3C%201.0%20kg&width=200&wktString=ENVELOPE%28-78.013916015625%2C-75.816650390625%2C39.740986355883564%2C38.03078569382294%29&zoom=7

**Comment by jhammock** [comment]
Lovely! Nice quick fix button :)
