### ISSUE TITLE
About checklist status

### ISSUE THREAD

**Issue by yrhe** [jhpoelen/effechecka#40]
For Effechecka 2.0

When add Aves and Insecta, then click "request checklist" button, the "checklist status" shows [ready]. And the checklists are displayed below. 

When click "refresh" button, the "checklist status" shows [downloading...] and then [linking to EOL pages...]. Not very sure what does "linking to EOL pages..." mean here. 

Then if keep Aves and Insecta in taxa box, and add "bodyMass > 10 kg", then click  "request checklist" button again. Then "checklist status" shows [requesting checklist...] first, and then [requested]. But there is not any checklist show up. This might make people wonder what does [requested] mean, and why although the data are requested, but nothing show up. Probably making the answer to "checklist status" clearer by explicitly showing something like [Could not find match data in the datasets/database]. And in the checklist area, rather than showing nothing, showing "0 checklist item" could be helpful for data users to understand the result of requesting checklist.

**Comment by jhpoelen** [comment]
Thanks for your comments! 

About the checklist status - the checklist "lifecycle" is now as follows:

1. user requests a checklist 
2. effechecka receives the requests (status = ```requesting check list```) and checks whether the results for that checklists already exists.
3a. if the checklist is not ready yet, nothing happens (status = ```requested```)
3b. (when checklist exists) the entire checklist is downloaded (actually up to 4096 items, status = ```downloading....```) 
4. now that the checklist is available locally (in the browser), the names are associated to eol page ids (status = ```linking to EOL pages....```) 
5. once the name are associated, the user can download the eol page id list in addition to save the checklist to a EOL collection.

I am hoping that you can help me make the status text more descriptive. Now that you know what happens in the background, which status texts would be more descriptive for you?

Regarding the empty checklist: in #39 I offered a first pass at making it clear when a checklist is empty and suggest next action. Please review the solution and comment on that issue if you have ideas on improving this.

Curious to hear your feedback on this.


 user action | effechecka action | checklist status
--- | --- | ---
user requests a checklist  | requesting checklist

**Comment by yrhe** [comment]
Hi Jorrit,

Thank you very much for your reply and explaining the details how checklist
status works!

I will think it more, check #39, and reply to you later.

Hope you have nice day!

Best wishes
Yurong

On Thu, Nov 12, 2015 at 12:18 PM, Jorrit Poelen <notifications@github.com>
wrote:

> Thanks for your comments!
>
> About the checklist status - the checklist "lifecycle" is now as follows:
>
>    1. user requests a checklist
>    2. effechecka receives the requests (status = requesting check list)
>    and checks whether the results for that checklists already exists. 3a. if
>    the checklist is not ready yet, nothing happens (status = requested)
>    3b. (when checklist exists) the entire checklist is downloaded (actually up
>    to 4096 items, status = downloading....)
>    3. now that the checklist is available locally (in the browser), the
>    names are associated to eol page ids (status = linking to EOL pages....)
>
>    4. once the name are associated, the user can download the eol page id
>    list in addition to save the checklist to a EOL collection.
>
> I am hoping that you can help me make the status text more descriptive.
> Now that you know what happens in the background, which status texts would
> be more descriptive for you?
>
> Regarding the empty checklist: in #39
> <https://github.com/jhpoelen/effechecka/issues/39> I offered a first pass
> at making it clear when a checklist is empty and suggest next action.
> Please review the solution and comment on that issue if you have ideas on
> improving this.
>
> Curious to hear your feedback on this.
> user action effechecka action checklist status user requests a checklist requesting
> checklist
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhpoelen/effechecka/issues/40#issuecomment-156171881>.
>



-- 
Best,
Yurong

**Comment by yrhe** [comment]
@jhpoelen @jhammock After knowing the lifecycle of checklist status, [requested] makes sense to me. But I still consider myself as a new user who do not the how it works at the backstage. How about [request ends/ended] or [request finishes/finished]. Does this English make sense to you? If the changes can make a user understand that the computer has run his/her current request and the current request has ended, then together with the changes mentioned in #39 , it could be clear enough for the user to understand what happen to his/her request. 

[working on your checklist] might make a user think "oh, the computer is still running my request, should I wait or do something else".

**Comment by jhammock** [comment]
I would like a word or two that suggests the checklist is not ready yet, ("working"?) but would also like a hint that clicking the refresh button is needed to see if it's ready.

@jhpoelen is it easy to change the status message when the request has completed? i.e., is it just showing the checklist results that is hard to automate? That would be the moment when "request finished" would be appropriate. It doesn't matter so much what the status message is, once you have a checklist to look at...

**Comment by yrhe** [comment]
Ref #39 again here, can we add a few words to "Your search retrieved zero results. Bummer! You might try..."? Like this: "Your search retrieved zero results. Bummer! The checklist is not ready, you might try..."

**Comment by jhammock** [comment]
Hmm... there is a difference between the checklist not being ready *yet* and the search being completed but not having any results. I think it's important that the wording for the two distinguish them clearly.

**Comment by yrhe** [comment]
I agree. These two are different.

I wonder how important/necessary we should let users know the status of
checklist, or whether users would care to see the checklist status?

In many other search scenarios, take google search as the simplest example,
I input the key words in search box, and click search, and then see the
search results: how many and what are they. I did not see the status of
searching. So I wonder if we don't show the checklist status, just only
show the results, would it less likely to confuse users? If users don't see
any results (i.e., zero item, no checklist), they will know that there is
no checklist, or the checklist is not ready yet. And with the words that
prompt them to change parameters, the users can try to start a new request.


On Fri, Nov 13, 2015 at 1:25 PM, Jen Hammock <notifications@github.com>
wrote:

> Hmm... there is a difference between the checklist not being ready *yet*
> and the search being completed but not having any results. I think it's
> important that the wording for the two distinguish them clearly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhpoelen/effechecka/issues/40#issuecomment-156509169>.
>



-- 
Best,
Yurong

**Comment by jhammock** [comment]
I agree that seeing your search results eliminates the need for a status message. We have a problem google doesn't have, though, in that our searchers may need to wait several minutes for their results. The refresh button is also a challenge google users don't face. 

Perhaps only one status is needed, whatever we decide to call it? Between when you hit the submit button, and when your results (or your Bummer, no results message) appear?

**Comment by yrhe** [comment]
I see, if the searching takes time, showing status is useful.

Showing only one status sounds good. Then I vote for showing it when you
hit the submit button (i.e., request checklist button on Effechecka 2.0).
And for the only one status, how about we use what you suggest early, [working
on your checklist]? Then show the results, no matter zero item, or a lot of
items in a checklist.

On Fri, Nov 13, 2015 at 3:12 PM, Jen Hammock <notifications@github.com>
wrote:

> I agree that seeing your search results eliminates the need for a status
> message. We have a problem google doesn't have, though, in that our
> searchers may need to wait several minutes for their results. The refresh
> button is also a challenge google users don't face.
>
> Perhaps only one status is needed, whatever we decide to call it? Between
> when you hit the submit button, and when your results (or your Bummer, no
> results message) appear?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhpoelen/effechecka/issues/40#issuecomment-156544709>.
>



-- 
Best,
Yurong

**Comment by jhpoelen** [comment]
thanks for sharing your thoughts on this. should I change the 
[requested] status to [working on your checklist...] ?

**Comment by jhammock** [comment]
Yes, let's try that. And maybe we can find a naive user or two to spring that on and see what they say :)

**Comment by yrhe** [comment]
Sounds great! :)

At least, we can ask Andrea, Jenny, Michele, and Sea to have a look first,
see whether they understand it.

On Fri, Nov 13, 2015 at 4:05 PM, Jen Hammock <notifications@github.com>
wrote:

> Yes, let's try that. And maybe we can find a naive user or two to spring
> that on and see what they say :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhpoelen/effechecka/issues/40#issuecomment-156556516>.
>



-- 
Best,
Yurong

**Comment by jhpoelen** [comment]
@yrhe @jhammock thanks for the discussion. I've changed the status message as suggested. Please re-open or comment if you have more ideas on this specific topic.
