### ISSUE TITLE
Label change for checklist statuses

### ISSUE THREAD

**Issue by jhammock** [jhpoelen/effechecka#41]
I think the statuses for a checklist are 
[requesting] (flashes by very fast, only noticed it once)
[requested]
[downloading] (also very fast? I've heard of this, but not seen it.)
[ready] 
then [linking to EOL pages], then back to [ready]

could we have [working on your checklist] instead of [requested] ?

**Comment by jhammock** [comment]
@yhre, what do you think?

**Comment by jhammock** [comment]
duplicate, closing

**Comment by jhpoelen** [comment]
ref to other issue #40 for completeness
