### ISSUE TITLE
About help users to understand "linking to EOL" and "save as EOL colllection" 

### ISSUE THREAD

**Issue by yrhe** [jhpoelen/effechecka#43]
One more thing I am not sure whether it should be put under the previous ticket, but still somewhat relevant.  

As we want to have as many people use the checklist as possible, not matter whether they are researchers or not, no matter whether they have used EOL before, I wonder is that possible a user would wonder what is EOL, why do I need all these data linked to EOL, why these pages should be saved to EOL collection, can I save it to somewhere else online? (different from downloading via json or csv).

Although there is EOL TraitBank link on the top of the webpage, maybe not all users would click the link to explore what it is, I guess many users come to use the checklist just directly go to request the data function.

So I wonder would it be helpful and practical to add something on the interface to help users, especially new users to understand why we link the data to EOL pages, and why we want them to use EO collection?

Thanks!

**Comment by jhpoelen** [comment]
@yrhe thanks for sharing your ideas on this. I can see how new users might get confused about this. I've added a "?" with a link to our [wiki](https://github.com/jhpoelen/effechecka/wiki/About#saving-as-eol-collection). Please feel free to add info to the wiki.
If you have another idea to help familiarize the user with what is going on, please re-open or comment on this issue.

**Comment by yrhe** [comment]
Thank you!

On Fri, Nov 13, 2015 at 10:56 PM, Jorrit Poelen <notifications@github.com>
wrote:

> Closed #43 <https://github.com/jhpoelen/effechecka/issues/43>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhpoelen/effechecka/issues/43#event-464295743>.
>



-- 
Best,
Yurong
