### ISSUE TITLE
link back from EOL collection not working

### ISSUE THREAD

**Issue by jhammock** [jhpoelen/effechecka#45]
Tiny bug revealed in tiny bug test collection http://eol.org/collections/122315

"regional search" looks like a link but doesn't act like one...

**Comment by jhpoelen** [comment]
Thanks for letting me know. This was caused by running a local version of effechecka, where the url is not defined. Running it on the online version does result in the link showing up . . . see http://eol.org/collections/122318 . So, the linkage seems to be working ok for non-local deployments.
