### ISSUE TITLE
API service is down

### ISSUE THREAD

**Issue by mjcollin** [jhpoelen/effechecka#54]
Service is down again as of 1:20 pm EST 1/29.

**Comment by eliagbayani** [comment]
Somebody may have fixed it already. API is back.

But I realized when I tried to ssh to c18node15 as user int.
I'm given this message: "Permission denied (publickey)."
I assume server was moved and old publickeys were not added.
To whom should I give my publickey to it can be added to /homedir/.ssh/authorized_keys ?
Thanks.

**Comment by mjcollin** [comment]
Issue was that server was out of disk space on that partition. @godfoder fixed it.
