### ISSUE TITLE
blank result

### ISSUE THREAD

**Issue by diatomsRcool** [jhpoelen/effechecka#57]
What does a blank result mean? I'm trying this url
http://api.effechecka.org/checklist?limit=20&taxonSelector=Animalia&wktString=ENVELOPE(1.448%2C42.604%2C1.549%2C42.656%2C1.787%2C42.575%2C1.705%2C42.489%2C1.517%2C42.428%2C1.407%2C42.486%2C1.467%2C42.51%2C1.412%2C42.534%2C1.448%2C42.604)&

**Comment by jhammock** [comment]
Looks like you have a separator problem...

**Comment by diatomsRcool** [comment]
I've tried a ton of different separators....What do you recommend? It doesn't work with spaces either.

**Comment by diatomsRcool** [comment]
http://api.effechecka.org/checklist?limit=20&taxonSelector=Aves%20Insecta&wktString=ENVELOPE(1.448%2042.604%201.549%2042.656%201.787%2042.575%201.705%2042.489%201.517%2042.428%201.407%2042.486%201.467%2042.51%201.412%2042.534%201.448%2042.604)&
No dice

**Comment by jhammock** [comment]
%20 between lat and long, and %2C%20 between pairs, is what I've seen...

**Comment by jhpoelen** [comment]
one way to troubleshoot your wktString is to replace api.effechecka.org/checklist?... with effechecka.org/?... . If the shape is well-formed, it should be displayed on the map.

example:
[plants, animals, fungi and insects in McLaren park](http://www.effechecka.org/?limit=20&taxonSelector=Plantae%2CAnimalia%2CFungi%2CInsecta&traitSelector=&wktString=POLYGON%20%28%28-122.4330997467041%2037.71340528823683%2C%20-122.4312114715576%2037.716189094052226%2C%20-122.42872238159178%2037.715849611138026%2C%20-122.42734909057616%2037.71435586783596%2C%20-122.42408752441405%2037.72318209600067%2C%20-122.42211341857909%2037.72392888243679%2C%20-122.41327285766602%2037.72331787591273%2C%20-122.4111270904541%2037.7192443702799%2C%20-122.40820884704588%2037.7192443702799%2C%20-122.4100112915039%2037.716324886782324%2C%20-122.41464614868164%2037.715917507845305%2C%20-122.41730690002441%2037.71320159102185%2C%20-122.4228000640869%2037.71394847807249%2C%20-122.42305755615234%2037.71034977121454%2C%20-122.4330997467041%2037.71340528823683%29%29)

and it's [api counterpart](http://api.effechecka.org/checklist?limit=20&taxonSelector=Plantae%2CAnimalia%2CFungi%2CInsecta&traitSelector=&wktString=POLYGON%20%28%28-122.4330997467041%2037.71340528823683%2C%20-122.4312114715576%2037.716189094052226%2C%20-122.42872238159178%2037.715849611138026%2C%20-122.42734909057616%2037.71435586783596%2C%20-122.42408752441405%2037.72318209600067%2C%20-122.42211341857909%2037.72392888243679%2C%20-122.41327285766602%2037.72331787591273%2C%20-122.4111270904541%2037.7192443702799%2C%20-122.40820884704588%2037.7192443702799%2C%20-122.4100112915039%2037.716324886782324%2C%20-122.41464614868164%2037.715917507845305%2C%20-122.41730690002441%2037.71320159102185%2C%20-122.4228000640869%2037.71394847807249%2C%20-122.42305755615234%2037.71034977121454%2C%20-122.4330997467041%2037.71340528823683%29%29)

**Comment by diatomsRcool** [comment]
Still having major trouble with this.
http://api.effechecka.org/checklist?limit=20&taxonSelector=Insecta&traitSelector=&wktString=POLYGON%2C%28%281.448%2042.604%2C%201.549%2042.656%2C%201.787%2042.575%2C%201.705%2042.489%2C%201.517%2042.428%2C%201.407%2042.486%2C%201.467%2042.51%2C%201.412%2042.534%2C%201.448%2042.604%29%29

**Comment by jhpoelen** [comment]
On closer inspection, your call returned a code 400 "bad request". This made me wonder about the validity of the wktString arguments. I decoded the wktString in a javascript console:

```javascript
decodeURIComponent('POLYGON%2C%28%281.448%2042.604%2C%201.549%2042.656%2C%201.787%2042.575%2C%201.705%2042.489%2C%201.517%2042.428%2C%201.407%2042.486%2C%201.467%2042.51%2C%201.412%2042.534%2C%201.448%2042.604%29%29')
POLYGON,((1.448 42.604, 1.549 42.656, 1.787 42.575, 1.705 42.489, 1.517 42.428, 1.407 42.486, 1.467 42.51, 1.412 42.534, 1.448 42.604))
```

Notice the comma following the POLYGON. After removing the comma, the request 
```http://api.effechecka.org/checklist?limit=20&taxonSelector=Insecta&traitSelector=&wktString=POLYGON%28%281.448%2042.604%2C%201.549%2042.656%2C%201.787%2042.575%2C%201.705%2042.489%2C%201.517%2042.428%2C%201.407%2042.486%2C%201.467%2042.51%2C%201.412%2042.534%2C%201.448%2042.604%29%29```
returned a 200 code and a result string:

```javascript
{
  "selector": {
    "taxonSelector": "Insecta",
    "wktString": "POLYGON((1.448 42.604, 1.549 42.656, 1.787 42.575, 1.705 42.489, 1.517 42.428, 1.407 42.486, 1.467 42.51, 1.412 42.534, 1.448 42.604))",
    "traitSelector": ""
  },
  "status": "requested",
  "items": []
}
```
How did you generate the wktString?

**Comment by diatomsRcool** [comment]
I have code that is generating the wkt string from geonames polygons. 
Now I'm super confused. Is it ENVELOPE or POLYGON? I finally go this to work http://www.effechecka.org/?limit=20&taxonSelector=Aves%2CInsecta&traitSelector=&wktString=POLYGON%20%28%2842.604%201.448%2C%2042.656%201.549%2C%2042.575%201.787%2C%2042.489%201.705%2C%2042.428%201.517%2C%2042.486%201.407%2C%2042.51%201.467%2C%2042.534%201.412%2C%2042.604%201.448%29%29
but the corresponding api request does not 
http://api.effechecka.org/checklist?limit=20&taxonSelector=Insecta&wktString=ENVELOPE(42.604%201.448%2C%2042.656%201.549%2C%2042.575%201.787%2C%2042.489%201.705%2C%2042.428%201.517%2C%2042.486%201.407%2C%2042.51%201.467%2C%2042.534%201.412%2C%2042.604%201.448)&
the effechecka page says it is working on my checklist. How much time is usually required?

**Comment by diatomsRcool** [comment]
OK, so I was finally able to get this to work 
http://api.effechecka.org/checklist?limit=20&taxonSelector=Insecta&traitSelector=&wktString=POLYGON((42.604%201.448%2C%2042.656%201.549%2C%2042.575%201.787%2C%2042.489%201.705%2C%2042.428%201.517%2C%2042.486%201.407%2C%2042.51%201.467%2C%2042.534%201.412%2C%2042.604%201.448))
Still wondering about how much time is needed to make a checklist....

**Comment by jhpoelen** [comment]
Glad you a wktString to work. The ```ENVELOPE``` is used sometimes, but I believe is not technically part of the WKT specification (see https://en.wikipedia.org/wiki/Well-known_text). Initially, effechecka was using envelope, but is now using polygon and even translates from envelope to polygon if needed.

Please close this issue if you feel this issue has been resolved. 

PS As far as the timing goes, I'd suggest to contact @jhammock or @godfoder  in a separate issue or email.
