### ISSUE TITLE
response code and blank result

### ISSUE THREAD

**Issue by diatomsRcool** [jhpoelen/effechecka#62]
This is giving me a blank result
http://api.effechecka.org/checklist?limit=20&taxonSelector=Mammalia&traitSelector=&wktString=POLYGON%28%2860.879%2029.862%2C%2061.713%2031.376%2C%2060.586%2033.143%2C%2060.901%2033.537%2C%2060.478%2034.079%2C%2060.998%2034.633%2C%2061.191%2035.29%2C%2061.387%2035.562%2C%2062.302%2035.141%2C%2063.011%2035.428%2C%2063.141%2035.776%2C%2063.935%2036.04%2C%2064.615%2036.423%2C%2065.102%2037.236%2C%2065.766%2037.545%2C%2067.496%2037.272%2C%2067.899%2037.064%2C%2068.303%2037.106%2C%2068.813%2037.244%2C%2069.008%2037.301%2C%2069.367%2037.405%2C%2069.954%2037.564%2C%2070.183%2037.862%2C%2070.498%2038.118%2C%2070.873%2038.464%2C%2071.136%2038.4%2C%2071.332%2037.883%2C%2071.561%2036.757%2C%2072.67%2037.021%2C%2073.309%2037.462%2C%2073.746%2037.222%2C%2074.683%2037.404%2C%2074.747%2037.275%2C%2074.572%2037.034%2C%2074.152%2036.91%2C%2073.144%2036.894%2C%2072.214%2036.664%2C%2071.569%2036.329%2C%2071.485%2035.754%2C%2071.593%2035.498%2C%2071.536%2035.09%2C%2071.219%2034.748%2C%2071.007%2034.461%2C%2070.502%2033.944%2C%2069.992%2033.74%2C%2070.298%2033.426%2C%2069.876%2033.096%2C%2069.535%2032.866%2C%2069.323%2031.941%2C%2068.57%2031.828%2C%2068.287%2031.757%2C%2067.713%2031.521%2C%2067.763%2031.328%2C%2066.969%2031.313%2C%2066.387%2030.934%2C%2066.362%2029.968%2C%2064.353%2029.545%29%29

Even though this gives me a "working on your checklist"
http://www.effechecka.org/?limit=20&taxonSelector=Mammalia&traitSelector=&wktString=POLYGON%20%28%2860.879%2029.862%2C%2061.713%2031.376%2C%2060.586%2033.143%2C%2060.901%2033.537%2C%2060.478%2034.079%2C%2060.998%2034.633%2C%2061.191%2035.29%2C%2061.387%2035.562%2C%2062.302%2035.141%2C%2063.011%2035.428%2C%2063.141%2035.776%2C%2063.935%2036.04%2C%2064.615%2036.423%2C%2065.102%2037.236%2C%2065.766%2037.545%2C%2067.496%2037.272%2C%2067.899%2037.064%2C%2068.303%2037.106%2C%2068.813%2037.244%2C%2069.008%2037.301%2C%2069.367%2037.405%2C%2069.954%2037.564%2C%2070.183%2037.862%2C%2070.498%2038.118%2C%2070.873%2038.464%2C%2071.136%2038.4%2C%2071.332%2037.883%2C%2071.561%2036.757%2C%2072.67%2037.021%2C%2073.309%2037.462%2C%2073.746%2037.222%2C%2074.683%2037.404%2C%2074.747%2037.275%2C%2074.572%2037.034%2C%2074.152%2036.91%2C%2073.144%2036.894%2C%2072.214%2036.664%2C%2071.569%2036.329%2C%2071.485%2035.754%2C%2071.593%2035.498%2C%2071.536%2035.09%2C%2071.219%2034.748%2C%2071.007%2034.461%2C%2070.502%2033.944%2C%2069.992%2033.74%2C%2070.298%2033.426%2C%2069.876%2033.096%2C%2069.535%2032.866%2C%2069.323%2031.941%2C%2068.57%2031.828%2C%2068.287%2031.757%2C%2067.713%2031.521%2C%2067.763%2031.328%2C%2066.969%2031.313%2C%2066.387%2030.934%2C%2066.362%2029.968%2C%2064.353%2029.545%2C%2060.879%2029.862%29%29

Any thoughts as to why? What is the response code for the first one?

**Comment by diatomsRcool** [comment]
Meanwhile....
This one works
http://api.effechecka.org/checklist?limit=20&taxonSelector=Mammalia&traitSelector=&wktString=POLYGON((1.448%2042.604%2C%201.549%2042.656%2C%201.787%2042.575%2C%201.705%2042.489%2C%201.517%2042.428%2C%201.407%2042.486%2C%201.467%2042.51%2C%201.412%2042.534%2C%201.448%2042.604))
And gives this
{
  "selector": {
    "taxonSelector": "Mammalia",
    "wktString": "POLYGON((1.448 42.604, 1.549 42.656, 1.787 42.575, 1.705 42.489, 1.517 42.428, 1.407 42.486, 1.467 42.51, 1.412 42.534, 1.448 42.604))",
    "traitSelector": ""
  },
  "status": "requested",
  "items": []
}

**Comment by jhammock** [comment]
http://api.effechecka.org/checklist?limit=20&taxonSelector=Mammalia&traitSelector=&wktString=POLYGON%20%28%2860.879%2029.862%2C%2061.713%2031.376%2C%2060.586%2033.143%2C%2060.901%2033.537%2C%2060.478%2034.079%2C%2060.998%2034.633%2C%2061.191%2035.29%2C%2061.387%2035.562%2C%2062.302%2035.141%2C%2063.011%2035.428%2C%2063.141%2035.776%2C%2063.935%2036.04%2C%2064.615%2036.423%2C%2065.102%2037.236%2C%2065.766%2037.545%2C%2067.496%2037.272%2C%2067.899%2037.064%2C%2068.303%2037.106%2C%2068.813%2037.244%2C%2069.008%2037.301%2C%2069.367%2037.405%2C%2069.954%2037.564%2C%2070.183%2037.862%2C%2070.498%2038.118%2C%2070.873%2038.464%2C%2071.136%2038.4%2C%2071.332%2037.883%2C%2071.561%2036.757%2C%2072.67%2037.021%2C%2073.309%2037.462%2C%2073.746%2037.222%2C%2074.683%2037.404%2C%2074.747%2037.275%2C%2074.572%2037.034%2C%2074.152%2036.91%2C%2073.144%2036.894%2C%2072.214%2036.664%2C%2071.569%2036.329%2C%2071.485%2035.754%2C%2071.593%2035.498%2C%2071.536%2035.09%2C%2071.219%2034.748%2C%2071.007%2034.461%2C%2070.502%2033.944%2C%2069.992%2033.74%2C%2070.298%2033.426%2C%2069.876%2033.096%2C%2069.535%2032.866%2C%2069.323%2031.941%2C%2068.57%2031.828%2C%2068.287%2031.757%2C%2067.713%2031.521%2C%2067.763%2031.328%2C%2066.969%2031.313%2C%2066.387%2030.934%2C%2066.362%2029.968%2C%2064.353%2029.545%2C%2060.879%2029.862%29%29

just worked for me...

**Comment by diatomsRcool** [comment]
When you say worked.....what did you see on the screen?

**Comment by diatomsRcool** [comment]
Hmmm. It just worked for me too. I got this result
{
  "selector": {
    "taxonSelector": "Mammalia",
    "wktString": "POLYGON ((60.879 29.862, 61.713 31.376, 60.586 33.143, 60.901 33.537, 60.478 34.079, 60.998 34.633, 61.191 35.29, 61.387 35.562, 62.302 35.141, 63.011 35.428, 63.141 35.776, 63.935 36.04, 64.615 36.423, 65.102 37.236, 65.766 37.545, 67.496 37.272, 67.899 37.064, 68.303 37.106, 68.813 37.244, 69.008 37.301, 69.367 37.405, 69.954 37.564, 70.183 37.862, 70.498 38.118, 70.873 38.464, 71.136 38.4, 71.332 37.883, 71.561 36.757, 72.67 37.021, 73.309 37.462, 73.746 37.222, 74.683 37.404, 74.747 37.275, 74.572 37.034, 74.152 36.91, 73.144 36.894, 72.214 36.664, 71.569 36.329, 71.485 35.754, 71.593 35.498, 71.536 35.09, 71.219 34.748, 71.007 34.461, 70.502 33.944, 69.992 33.74, 70.298 33.426, 69.876 33.096, 69.535 32.866, 69.323 31.941, 68.57 31.828, 68.287 31.757, 67.713 31.521, 67.763 31.328, 66.969 31.313, 66.387 30.934, 66.362 29.968, 64.353 29.545, 60.879 29.862))",
    "traitSelector": ""
  },
  "status": "requested",
  "items": []
}

**Comment by jhammock** [comment]
yup, that

**Comment by diatomsRcool** [comment]
I'm realizing that I have to begin and end with the same coordinates.
