### ISSUE TITLE
intermittent unresponsiveness of effechecka api

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/effechecka#70]
After switch to hdfs, the api becomes unresponsive intermittently. 

Root cause - out of memory of the web api service. Good thing is that the process is automatically restarted by marathon (the infrastructure component that helps run the web api), the bad thing is that the api is intermittently unresponsive.

from mesos:
```
looking for [/guoda/data/monitor/source-of-monitored-occurrence/source=gbif]
looking for [/guoda/data/monitor/monitor-of-occurrence/u0=22/u1=4d/u2=51/uuid=224d5182-bc6c-5bcd-89f3-66529f5974a4/source=gbif]
[0m[[31merror[0m] [0m(pool-8-thread-1915) java.lang.OutOfMemoryError: Java heap space[0m
[0m[[31merror[0m] [0m(pool-8-thread-1974) java.lang.OutOfMemoryError: GC overhead limit exceeded[0m
```

**Comment by jhpoelen** [comment]
Another cause resulting in intermittent api failures is related to "too many open file" has been reported previously at https://github.com/bio-guoda/guoda-services/issues/22.

**Comment by jhpoelen** [comment]
@mjcollin FYI this is the issue that is caused the up-down-up behavior of the api.guoda.bio / api.effechecka.org . Am still working on it, happy to take your suggestions.

**Comment by mjcollin** [comment]
Disabled monitoring for now - remember to re-enable.

**Comment by jhpoelen** [comment]
Am able to reproduce the issue locally.

**Comment by jhpoelen** [comment]
Am no longer able to reproduce the issue locally after implementing an alternate method to access (or stream) parquet files for easy access through web api using akka-http / akka-streaming (see https://akka.io) and Apache's Parquet java library (see https://parquet.apache.org). I've re-used the path discovery and row class of https://github.com/51zero/eel-sdk instead of using the eel parquet reader.

@mjcollin please feel free to re-enable the monitoring - the api seems stable enough. 

@jhammock @diatomsRcool please holler if you see any weirdness with downloads/ data access to effechecka.org and/or gimmefreshdata.github.io . 

Please re-open / comment on this issue if this is not the case.
