### ISSUE TITLE
travis build fails after merge - related to docker 

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/effechecka#74]
@godfoder any idea why the travis build is failing?

See https://travis-ci.org/jhpoelen/effechecka/builds/264853593 .

**Comment by jhpoelen** [comment]
Looks like the error was introduced with docker dependencies.

**Comment by jhpoelen** [comment]
@godfoder suggest to either revert or resolve the issue.

**Comment by godfoder** [comment]
For some reason your builds are still running on the travis "percise" environment, and mine is running on "trusty". I'm not sure how to force travis to upgrade your build environment without pinning it to trusty (which would be fine for now, but would cause similar problems later).

**Comment by jhpoelen** [comment]
Ah, I see. https://travis-ci.org/bio-guoda/effechecka did succeed. Looks like travis is still in the process of migrating https://travis-ci.org/jhpoelen/effechecka to the new trusty environment. I'll enable a cron job to run daily.

**Comment by jhpoelen** [comment]
Also, if it would help reduce friction by moving jhpoelen/effechecka to bio-guoda/effechecka (with issues, wiki etc), you should be able to do so.

**Comment by jhpoelen** [comment]
Hmm. The travis config now assumes docker hub image bioguoda/effechecka . Perhaps best to reconcile the two repositories to avoid confusion. @godfoder Agree?

**Comment by jhpoelen** [comment]
issue no longer relevant as https://github.com/bio-guoda/effechecka is used for deployment/development.
