### ISSUE TITLE
antarctica

### ISSUE THREAD

**Issue by diatomsRcool** [jhpoelen/effechecka#79]
Am I not able to get a checklist for Antarctica?
I get a bad result with this query
http://api.effechecka.org/checklist.tsv?traitSelector=&wktString=POLYGON%20%28%28-178.59375%20-85.1709701284095%2C%20-178.59375%20-73.84928645675247%2C%20-150.46875%20-72.63337363853837%2C%20-125.15625000000001%20-70.4073476760681%2C%20-102.65625%20-69.4421276134176%2C%20-81.5625%20-69.4421276134176%2C%20-67.5%20-57.75107598132101%2C%20-45%20-61.98026726504402%2C%20-50.625%20-70.4073476760681%2C%20-46.40625%20-74.61344527005673%2C%20-18.28125%20-67.37369797436554%2C%2023.90625%20-66.26685631430843%2C%2052.03125%20-61.98026726504402%2C%2075.9375%20-64.51064316846676%2C%20123.74999999999999%20-62.633769607868125%2C%20161.71874999999997%20-65.10914820386473%2C%20174.375%20-71.7739410364347%2C%20177.18749999999997%20-84.8024737243345%2C%20-178.59375%20-85.1709701284095%29%29

**Comment by jhpoelen** [comment]
This is a known limitation https://github.com/locationtech/spatial4j/is
sues/126 in the library used to parse the wktString and do the spatial
mapping:
pole wrapping is not supported.

**Comment by jhammock** [comment]
@diatomsRcool I think you need a latitude segment explicitly ending at, or possibly just north of, 90 degrees South, and, I think, also an "edge" running from the pole to the northward edge of the polygon.
