### ISSUE TITLE
include GBIF occurrence data in checklist generation process

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/effechecka#8]
Currently, only iDigBio's archive (https://s.idigbio.org/idigbio-static-downloads/idigbio.zip) is used to calculate checklists given taxonomic and spatial constraints.

We'd like to add occurrence data from GBIF to increase the coverage of the checklist generator. Also, we'd like to show that we can generate a single checklist from separate occurrence data sources.

**Comment by jhpoelen** [comment]
Today, @jhammock re-confirmed the need to include GBIF in addition to the iDigBio dataset for purpose of checklist generation.

**Comment by jhpoelen** [comment]
@jhammock gbif occurrence records now included by default in effechecka, along with idigbio specimen records.

According to [Oaklands Lake Merritt checklist](http://www.effechecka.org/#height=120&lat=37.80354511753136&limit=20&lng=-122.25688934326172&taxonSelector=Aves%2CMammalia&traitSelector=&width=94&wktString=ENVELOPE%28-122.27302551269531%2C-122.24075317382812%2C37.819819234520956%2C37.78726741375342%29&zoom=12), fox squirrels (_Procyon lotor_) and raccoons (_Sciurus niger_) hang out near the lake. Who knew?

Please let me know if you find any issues with this.

**Comment by jhammock** [comment]
yayyyy! @holmesjtg @mariestuder please try this out in your exotic locations and let us know if it's behaving as expected?

**Comment by jhpoelen** [comment]
please do note that due to volume (~450M occurrence records) and available hardware, it takes about 10min for a checklist to generate. If this is a constraint, we might want to consider to dedicate more hardware to crunching the lists.

**Comment by holmesjtg** [comment]
Okay, thanks for that info. I'm excited to give it a trial run... maybe 
later in the week!

Cheers,
Jeff

**Comment by jhammock** [comment]
Thanks, Jorrit! Any guesses how long just to fetch occurrence records?

**Comment by jhpoelen** [comment]
Fetching occurrence records would actually be faster. . . checklists are the worst case performance because you have to aggregate after filtering (e.g. by name, location, trait) occurrence records before coughing up a list. With straight up occurrence records, no aggregation is needed and results can be provided when needed. I am hoping that the "freshdata" use cases will help uncover more specific performance numbers related to this. More on that later!

**Comment by jhpoelen** [comment]
GBIF is used to build checklists as noted earlier.
