### ISSUE TITLE
server problem?

### ISSUE THREAD

**Issue by diatomsRcool** [jhpoelen/effechecka#80]
I'm getting lots of messages
"The server is currently unavailable (because it is overloaded or down for maintenance)."
when making checklists. Is there a problem with the server?

**Comment by jhammock** [comment]
The cluster wasn't very active, according to jupyter. I stopped a couple of servers, leaving just one active. I'm not running anything myself.

**Comment by jhammock** [comment]
oops, this should probably be reported in https://github.com/bio-guoda/guoda-services/issues if that didn't happen to get you unstuck.

**Comment by jhpoelen** [comment]
duplicate of https://github.com/bio-guoda/guoda-services/issues/39 . Closing issue.
