### ISSUE TITLE
Website stalls

### ISSUE THREAD

**Issue by turnerh** [jhpoelen/effechecka#81]
I came across a reference to Effechecka and Freshdata in a paper submitted for a special issue for Apps Plant Syst dedicated to TDWG and databasing nat hist collections. I tried to get effechecka to work, trying different settings on the website such as taxon Arytera (a sapindaceous plant genus) for the Tonga archipelago (one species there, represented in various large herbaria). However, I'm not doing it correctly because the app seems to stall, only showing that the checklist status is 'busy'. The URL is http://www.effechecka.org/?limit=20&taxonSelector=&traitSelector=&wktString=POLYGON%20%28%28-179.560546875%20-34.27537529764387%2C%20-179.560546875%20-2.5095731690398404%2C%20-163.388671875%20-2.5095731690398404%2C%20-163.388671875%20-34.27537529764387%2C%20-179.560546875%20-34.27537529764387%29%29

Is there a manual explaining the various possibilities (I checked the wiki) so that I can actually generate and download complete checklists with exact collecting localities for the specimens? The program seems great for me to generate distribution maps for my biogeographical research.
Hubert Turner 
http://members.casema.nl/arp/

**Comment by turnerh** [comment]
I noted an error in the URL given in my previous post: the taxon selector was still empty! However, after modification the search still does not give any result, with the same stalling issue . Herre is the modified URL (I also slightly simplified the area selection):
http://www.effechecka.org/?limit=20&taxonSelector=Arytera&traitSelector=&wktString=GEOMETRYCOLLECTION%28POLYGON%20%28%28-180%20-43%2C%20-180%2029%2C%20-139%2029%2C%20-139%20-43%2C%20-180%20-43%29%29%2CPOLYGON%20%28%2875%20-43%2C%2075%2029%2C%20180%2029%2C%20180%20-43%2C%2075%20-43%29%29%29
 I tried the big sharks example, and that ran properly. But I could not generate a list of all collection localities (latlong dat) for all selected specimens. Any way of doing that? It would be great if I could generate a map with all collection localities , e.g. with dots on the map used to circumscribe the area I'm interested in, preferably with the tagged localities linked to the label data for the specimen. Now all I can find are minute maps of the world with all collection localities worldwide of e.g. the big sharks occurring in the Gulf of Mexico.

**Comment by jhpoelen** [comment]
@turnerh looks like the outage has cleared, see https://github.com/bio-guoda/guoda-services/issues/44#issuecomment-362036522 .
