### ISSUE TITLE
Website stalled again??

### ISSUE THREAD

**Issue by turnerh** [jhpoelen/effechecka#82]
It seems the website is again stalled! I had two jobs running, but after 36 hrs still nothing had happened. Each time I refreshed the response was 'busy'. Here is one of the requests I made:
http://www.effechecka.org/?limit=20&taxonSelector=Sararanga&traitSelector=&wktString=GEOMETRYCOLLECTION%28POLYGON%20%28%28-180%20-43%2C%20-180%2029%2C%20-139%2029%2C%20-139%20-43%2C%20-180%20-43%29%29%2CPOLYGON%20%28%2875%20-43%2C%2075%2029%2C%20180%2029%2C%20180%20-43%2C%2075%20-43%29%29%29

There are only two species in the genus (in Pandanaceae), and both have a rather limited distribution (N. New Guinea and SE Philippines, resp.), so it should not be too hard to generate the checklist.

**Comment by jhammock** [comment]
Hang in there, @turnerh , it looks like some things are still in flight with our hosts at the GUODA project, see https://github.com/bio-guoda/guoda-services/issues/44#issuecomment-363227461

**Comment by mjcollin** [comment]
Checklists are currently running and completing at the rate of several an hour. I'll check back in with this tomorrow after I have hopefully gotten HDFS synced back up and checkpointed properly to make it a bit more safe to look at performance issues.

**Comment by jhammock** [comment]
Thanks, @mjcollin ! @turnerh be advised @diatomsRcool is running a very large batch of queries; that process runs 12 hours on 12 hours off, in order to give the rest of us a turn; it should be off during your business hours.
